name: Metrics
on:
  # Schedule updates
  schedule: [{ cron: '0 0 * * *' }]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: { branches: ['master', 'main'] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Advanced stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-commits-calendar.svg
          user: jpb06
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: regular
          config_timezone: Europe/Paris
          # Isometric commit calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Display full year instead of half year
          # Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C # Display achievements with rank C or higher
          plugin_achievements_secrets: yes # Display unlocked secrets achievements
          plugin_achievements_ignored: octonaut # Hide octonaut achievement
          plugin_achievements_limit: 0 # Display all unlocked achievement matching threshold and secrets params
          plugin_achievements_display: compact # or detailed
          # Coding habits
          plugin_habits: yes
          plugin_habits_from: 200 # Use 200 events to compute habits
          plugin_habits_days: 14 # Keep only events from last 14 days
          plugin_habits_facts: yes # Display facts section
          plugin_habits_charts: yes # Display charts section
          plugin_habits_trim: yes # Trim unused hours on daily chart
          # reactions
          plugin_reactions: yes
          plugin_reactions_limit: 200 # Compute reactions over last 200 issue comments
          plugin_reactions_limit_issues: 100 # Compute reactions over laste 100 issues/pull requests opened
          plugin_reactions_days: 30 # Compute reactions on issue comments posted less than 14 days ago
          plugin_reactions_details: count, percentage # Display reactions count and percentage
          plugin_reactions_ignored: bot # Ignore "bot" user
          # pull requests
          plugin_followup: yes
          plugin_followup_sections: repositories
