name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: '0 * * * *' }]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: { branches: ['master', 'main'] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: isometric-commits-calendar
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-commits-calendar.svg
          base: ''
          # Isometric commit calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Display full year instead of half year

      - name: achievements
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-achievements.svg
          base: ''
          # Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C # Display achievements with rank C or higher
          plugin_achievements_secrets: yes # Display unlocked secrets achievements
          plugin_achievements_ignored: octonaut # Hide octonaut achievement
          plugin_achievements_limit: 0 # Display all unlocked achievement matching threshold and secrets params
          plugin_achievements_display: compact # or detailed

      - name: most-used-language
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-most-used-language.svg
          base: ''
          # Most used languages
          plugin_languages: yes
          plugin_languages_ignored: html, css # List of languages to ignore
          plugin_languages_colors: '0:orange, javascript:#ff0000, ...' # Make most used languages orange and JavaScript red
          plugin_languages_aliases: 'JavaScript:JS, TypeScript:TS, ...' # Customize languages names with aliases
          plugin_languages_details: bytes-size, percentage # Additionally display total bytes size and percentage
          plugin_languages_threshold: 2% # Hides all languages less than 2%
          plugin_languages_limit: 8 # Display up to 8 languages
          plugin_languages_sections: most-used, recently-used # Display most used and recently used languages stats
          plugin_languages_indepth: no # Get indepth stats (see documentation before enabling)
          plugin_languages_categories: programming # Display only languages that match these categories in most-used section
          plugin_languages_recent_categories: markup, programming, data # Display only languages that match these categories in recently-used section
          plugin_languages_recent_load: 500 # Load up to 500 events to compute recently used stats
          plugin_languages_recent_days: 14 # Limit recently used stats to last week
          commits_authoring: ${{ secrets.AUTHOR_EMAILS }} # Surnames or email addresses used to identify your commits

      - name: coding-habits
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          filename: coding-habits.svg
          base: ''
          # Coding habits
          plugin_habits: yes
          plugin_habits_from: 200 # Use 200 events to compute habits
          plugin_habits_days: 14 # Keep only events from last 14 days
          plugin_habits_facts: yes # Display facts section
          plugin_habits_charts: yes # Display charts section
          plugin_habits_trim: yes # Trim unused hours on daily chart
          config_timezone: Europe/Paris # Set timezone

      - name: reactions
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          filename: reactions.svg
          base: ''
          # reactions
          plugin_reactions: yes
          plugin_reactions_limit: 200 # Compute reactions over last 200 issue comments
          plugin_reactions_limit_issues: 100 # Compute reactions over laste 100 issues/pull requests opened
          plugin_reactions_days: 30 # Compute reactions on issue comments posted less than 14 days ago
          plugin_reactions_details: count, percentage # Display reactions count and percentage
          plugin_reactions_ignored: bot # Ignore "bot" user

      - name: pull-requests
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          filename: pull-requests.svg
          base: ''
          # pull requests
          user: jpb06
          template: classic
          config_timezone: Europe/Paris
          plugin_followup: yes
          plugin_followup_sections: repositories

      - name: stats
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          filename: stats.svg
          user: jpb06
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large
          config_timezone: Europe/Paris
